run *ARGS:
    cd ../../ && npx tsx ./Dev/StandAlone/index.ts {{ARGS}}

watch *ARGS:
    cd ../../ && ./watch.sh --cooldown 1 --exclude "./Dev/Server/watch" "npx tsx ./Dev/StandAlone/index.ts {{ARGS}}"

