[package]
name = "stoff_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"

spade = "2"
geo = "0.32"
getrandom = { version = "0.2", features = ["js"] }
kdtree = {version = "0.7.0", default-features = false}
web-sys = { version = "0.3", features = ["console"] }
petgraph = "0.8"
rustc-hash = "2.1.2"

clahe = "0.1.2"
image = "0.25.10"

[profile.dev]
debug = true  # Ensure this is set to true (or 1 / 2)
