[workspace]
members = [
    "crates/minimum_weight_perfect_matching",
    "crates/geometry",
    "crates/procedual_art",
    "crates/wasm",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/Felix-Paetsch/stoff"
license = "Apache License 2.0"

[workspace.dependencies]
itertools = "0.14.0"
petgraph = "0.8"
union-find = "0.4.4"
log = "0.4"
image = "0.25.10"
