set shell := ["bash", "-euo", "pipefail", "-c"]

sync:
    uv sync --locked

run:
    uv run python index.py

watch:
    ../watch.sh --fileEndings py "uv run python index.py"

python *args:
    uv run python {{args}}

install package:
    uv add {{package}}

uninstall package:
    uv remove {{package}}

add-dev package:
    uv add --dev {{package}}

remove-dev package:
    uv remove --dev {{package}}

lock:
    uv lock

update:
    uv lock --upgrade

format:
    uv run ruff format .

lint_hot:
    ../watch.sh --fileEndings py "uv run ruff check ."

lint:
    uv run ruff check .

lint-fix:
    uv run ruff check . --fix
